// Code generated by MockGen. DO NOT EDIT.
// Source: ./operation.go

// Package mock_operation is a generated GoMock package.
package mock_operation

import (
	models "github.com/bullblock-io/tezTracker/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepo is a mock of Repo interface
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockRepo) List(kinds, inBlocks, accountIDs []string, limit, since int64) ([]models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", kinds, inBlocks, accountIDs, limit, since)
	ret0, _ := ret[0].([]models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockRepoMockRecorder) List(kinds, inBlocks, accountIDs, limit, since interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepo)(nil).List), kinds, inBlocks, accountIDs, limit, since)
}
